POST http://localhost:4000/user/login
Content-Type: application/json

{
  "email": "jwt@rest.com",
  "password": "letsseeifthisjwtworks"
}
###

GET http://localhost:4000/feed
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjMsImVtYWlsIjoiand0QHJlc3QuY29tIiwicGFzc3dvcmQiOiIkMmEkMTIkVjhhd1FMb0RPTjI1d1JzOUdTUjhOLjdVQ1FsU2wxcnlaZWw0TWs4T2pEYXRYa2YwSGVXNmEiLCJuYW1lIjoiand0dGVzdCIsInVzZXJuYW1lIjoiand0dGVzdCIsImNyZWF0ZWRBdCI6IjIwMjEtMTItMTZUMTM6MzQ6MTguOTk0WiIsInVwZGF0ZWRBdCI6IjIwMjEtMTItMTZUMTM6MzQ6MTguOTk1WiIsImlhdCI6MTYzOTY5MzAwMX0.9ypBeATAw4aVArN6DUdtS_apVDadkqMfheC2wxKYCcg

